import { Icons } from "@/components/ui/icons";
import { type Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "breath-tracking",
    name: "Breath Tracking",
    subtitle: "实时呼吸监测研究",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/p7o28IXwsrs",
    dateRange: "2025年2月 - 2025年11月",
    techStack: "Python, Flask, YOLO, OpenCV",
    jobTypes: ["AIMR", "SRE"],
    bullets: [
      "训练YOLOv11n进行深度图人体检测，优化呼吸模式信号质量（相关性↑0.5，MSE↓59.1%）",
      "构建实时呼吸追踪流水线；优化Flask演示性能（渲染时间从1000ms降至150ms）",
    ],
  },
  {
    id: "biovis",
    name: "BioVis",
    subtitle: "MR生理信号监测研究",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/zOPQXXpSRbg",
    dateRange: "2025年5月 - 2025年11月",
    techStack: "Unity, Meta Quest 3, C#",
    jobTypes: ["AIMR", "SWE"],
    bullets: [
      "参与SIGGRAPH Asia XR论文投稿；负责代码实现并参与论文撰写",
      "在UBFC-rPPG数据集上验证rPPG（心率MAE 3.75 BPM，呼吸率MAE 2.45 BPM）",
    ],
  },
  {
    id: "shyu-resume",
    name: "ShYu Resume",
    subtitle: "开源项目",
    subtitleIcon: Icons.Github,
    link: "https://github.com/shyu216/shyu-resume",
    dateRange: "2024年8月 - 进行中",
    techStack: "Next.js, Tailwind",
    jobTypes: ["SRE"],
    bullets: [
      "构建基于Next.js的i18n简历生成器，支持中/英/港三语切换及A4 PDF导出（含超链接）",
      "部署至GitHub Pages，提供一键保存/打印功能；撰写完整README文档便于开发者上手",
    ],
  },
  {
    id: "carbon-2-garden",
    name: "Carbon 2 Garden",
    subtitle: "传感器交互应用",
    subtitleIcon: Icons.LayoutTemplate,
    link: "https://github.com/CRUVOD/CarbonTracker",
    dateRange: "2024年9月 - 2024年11月",
    techStack: "React Native, Google Maps API",
    jobTypes: ["SWE"],
    bullets: [
      "构建React Native环保习惯应用，包含任务系统、排行榜和活动提醒功能",
      "实现传感器融合（陀螺仪 + GPS + Maps API），交付\"久坐提醒+公园推荐\"原型",
    ],
  },
  // {
  //   id: "poetry-card",
  //   name: "诗词小卡片",
  //   subtitle: "开源项目",
  //   subtitleIcon: Icons.PackageOpen,
  //   link: "https://github.com/shyu216/ccpoems",
  //   dateRange: "2023年12月 - 2024年2月",
  //   techStack: "React Native, SQLite",
  //   bullets: [
  //     "使用React Native + SQLite开发古诗词App，实现本地CRUD、随机抽取、历史记录",
  //     "完成Android APK打包发布，为后续React Native项目积累工程经验",
  //   ],
  // },
  {
    id: "3d-object-detection",
    name: "3D目标检测",
    subtitle: "点云研究",
    subtitleIcon: Icons.GraduationCap,
    link: "https://github.com/shyu216/DPC",
    dateRange: "2022年9月 - 2023年5月",
    techStack: "PyTorch, Open3D, OpenPCDet, SLURM",
    jobTypes: ["AIMR"],
    bullets: [
      "基于OpenPCDet复现3D检测（KITTI）；↑行人AP 13.4%，↑车辆AP 5.7%",
      "独立完成本科毕业论文，系统整合研究方法和实验结果",
    ],
  },
  {
    id: "distributed-raft",
    name: "Raft共识算法Go实现",
    subtitle: "分布式系统",
    subtitleIcon: Icons.Code,
    link: "https://github.com/shyu216/go-raft",
    dateRange: "2022年1月 - 2022年5月",
    techStack: "Go, Raft",
    jobTypes: ["SRE"],
    bullets: [
      "研读并实现Raft共识算法原始论文；用Go编写领导者选举和日志复制逻辑",
      "交付稳定的分布式KV存储，支持自动领导者选举和数据一致性保证；通过所有测试用例",
    ],
  },
  // {
  //   id: "easy-draw-guess",
  //   name: "你画我猜",
  //   subtitle: "实时多人游戏 · CSCI3100",
  //   subtitleIcon: Icons.BookOpen,
  //   link: "https://github.com/easyDG",
  //   dateRange: "2022年1月 - 2022年5月",
  //   techStack: "NodeJS, Socket.IO",
  //   bullets: [
  //     "基于MySQL实现游戏账号管理，利用Socket.IO实现跨设备光标追踪与实时聊天",
  //     "部署于AWS EC2，支持多设备流畅演示",
  //   ],
  // },
  {
    id: "course-algorithm-practice",
    name: "数据与算法实践",
    subtitle: "课程项目集合",
    subtitleIcon: Icons.Code,
    link: "https://shyu216.github.io/knownoevil/study/",
    dateRange: "2021年9月 - 2024年5月",
    techStack: "SQL, Hadoop, Python",
    jobTypes: ["SWE"],
    bullets: [
      "设计Hadoop/MapReduce流水线并行实现Dijkstra、PageRank、K-Means；优化大数据处理流程",
      "构建Splendor规划智能体，使用MDP和奖励函数建模；以27/40胜率击败TA基准（班级排名第4）",
    ],
  },
];
