import { Icons } from "@/components/ui/icons";
import { type Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "biovis",
    name: "BioVis",
    subtitle: "MR 生理信号监测 · 研究项目",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/zOPQXXpSRbg",
    dateRange: "2025年5月 - 2025年11月",
    techStack: "Unity, Meta Quest 3, C#",
    bullets: [
      "协助导师完成 Siggraph Asia XR 论文投稿（第二作者），负责 MR 生理信号检测软件原型开发",
      "独立开发 6 场景、40+ 脚本的 Unity 项目，完成 3D 资源整合与 UI 搭建",
      "基于 ComputeShader 实现图像处理并行加速，复现 EVM 算法，完成 Quest 3 实时 MR 原型部署",
      "评估 ONNX、Sentis 模型量化与推理方案，在 Quest 3 完成 YOLO v11 nano 实时推理测试与对比",
      "复现多款 rPPG 算法并在多数据集完成性能验证，实现从学术评估到端侧实时部署",
    ],
    rank: 1,
  },
  {
    id: "shyu-resume",
    name: "ShYu Resume",
    subtitle: "个人简历 · 开源项目",
    subtitleIcon: Icons.Github,
    link: "https://github.com/shyu216/shyu-resume",
    dateRange: "2024年8月 - 进行中",
    techStack: "Next.js, Tailwind",
    bullets: [
      "开发基于 Next.js 的 i18n 简历生成器，支持中/英/港三语切换及 A4 PDF 导出（含超链接）",
      "部署于 GitHub Pages，提供一键保存/打印入口",
    ],
    rank: 1,
  },
  {
    id: "carbon-2-garden",
    name: "Carbon 2 Garden",
    subtitle: "传感器互动应用 · COMP90018",
    subtitleIcon: Icons.LayoutTemplate,
    link: "https://github.com/CRUVOD/CarbonTracker",
    dateRange: "2024年9月 - 2024年11月",
    techStack: "React Native, Firebase",
    bullets: [
      "开发 React Native 环保习惯 App，实现任务系统、排行榜、运动提醒",
      "集成陀螺仪传感器与 Google Maps API，完成“久坐提醒 + 公园推荐”互动挑战原型",
      "负责路由设计及项目骨架，完成 APK 打包发布",
    ],
    rank: 1,
  },
  {
    id: "poetry-card",
    name: "诗词小卡片",
    subtitle: "本地数据库 · 开源项目",
    subtitleIcon: Icons.PackageOpen,
    link: "https://github.com/shyu216/ccpoems",
    dateRange: "2023年12月 - 2024年2月",
    techStack: "React Native, SQLite",
    bullets: [
      "使用 React Native + SQLite 开发古诗词 App，实现本地 CRUD、随机抽取、历史记录",
      "完成 Android APK 打包发布，为后续 React Native 项目积累工程经验",
    ],
    rank: 2,
  },
  {
    id: "3d-object-detection",
    name: "三维目标检测",
    subtitle: "点云 · 本科毕设",
    subtitleIcon: Icons.GraduationCap,
    link: "https://github.com/shyu216/DPC",
    dateRange: "2022年9月 - 2023年5月",
    techStack: "Python, PyTorch, Open3D",
    bullets: [
      "基于 OpenPCDet 复现 3D 目标检测，在 KITTI 数据集生成车辆/行人/自行车检测框",
      "使用 SLURM 集群训练模型，通过 Open3D 完成点云可视化及实验结果分析",
      "独立完成本科毕业论文，系统整理检测方法与实验数据",
    ],
    rank: 1,
  },
  {
    id: "distributed-raft",
    name: "Raft 共识算法 Go 实现",
    subtitle: "分布式系统 · CSCI4160",
    subtitleIcon: Icons.Code,
    link: "https://github.com/shyu216/go-raft",
    dateRange: "2022年1月 - 2022年5月",
    techStack: "Go, Raft",
    bullets: [
      "研读 Raft 论文核心原理，基于论文要点实现 Raft 共识算法，通过 Leader 选举与日志复制核心模块测试",
      "实现支持线性一致性的分布式 KV 存储，修复锁竞争、日志提交推进等分布式系统典型并发问题，稳定通过所有测试用例",
    ],
    rank: 1,
  },
  {
    id: "easy-draw-guess",
    name: "你画我猜",
    subtitle: "实时多人游戏 · CSCI3100",
    subtitleIcon: Icons.BookOpen,
    link: "https://github.com/easyDG",
    dateRange: "2022年1月 - 2022年5月",
    techStack: "NodeJS, Socket.IO",
    bullets: [
      "基于 MySQL 实现游戏账号管理，利用 Socket.IO 实现跨设备光标追踪与实时聊天",
      "部署于 AWS EC2，支持多设备流畅演示",
    ],
    rank: 3,
  },
  {
    id: "course-algorithm-practice",
    name: "数据与算法落地",
    subtitle: "课程项目集合",
    subtitleIcon: Icons.Code,
    link: "https://shyu216.github.io/knownoevil/study/",
    dateRange: "2021年9月 - 2024年5月",
    techStack: "SQL, Hadoop, Python",
    bullets: [
      "基于 Hadoop/MapReduce 设计分布式算法系统，实现并行 Dijkstra、PageRank、K-Means，优化大数据处理流程",
      "设计 5 张带主键/外键约束的关联表，编写 8 个含多表联查/子查询/自定义公式的 SQL 查询，分析联赛/球队/赞助商的体育数据",
      "基于 PostGIS 实现空间 SQL 查询，实现单点高程查询、区域坡度统计等需求，覆盖地理距离计算、路径规划等场景",
      "针对 Splendor 游戏设计 AI 规划智能体，抽象 MDP 状态空间，设计奖励函数，击败 TA 基准（27 胜 13 负）",
    ],
    rank: 1,
  },
];
