import { Icons } from "@/components/ui/icons";
import { type Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "breath-tracking",
    name: "Breath Tracking",
    subtitle: "實時呼吸監測 · 研究項目",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/p7o28IXwsrs",
    dateRange: "2025年2月 - 2025年11月",
    techStack: "Python, Flask, YOLO, OpenCV",
    bullets: [
      "與 4DMedical 合作開發實時呼吸追蹤系統，用於觸發其 XV Scanner",
      "訓練 YOLOv11n 進行深度圖人體檢測，提升信號穩定性（相關係數 ↑0.5，MSE ↓59.1%）",
      "將 MATLAB EVM 算法重寫為 Python（OpenCV/NumPy），放大細微的呼吸運動",
      "構建實時呼吸追蹤管道；優化 Flask 演示（渲染時間從 1000ms 降至 150ms）",
    ],
  },
  {
    id: "biovis",
    name: "BioVis",
    subtitle: "MR 生理信號監測 · 研究項目",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/zOPQXXpSRbg",
    dateRange: "2025年5月 - 2025年11月",
    techStack: "Unity, Meta Quest 3, C#",
    bullets: [
      "合著（第二作者）SIGGRAPH Asia XR 投稿；構建 MR 生理信號檢測原型（Unity）",
      "獨立開發 Unity 專案（6 場景，40+ 腳本），完成 3D/UI 集成",
      "透過 ComputeShader 複現 EVM；在 Meta Quest 3 上部署",
      "在 Quest 3 上對 YOLOv11n 進行基準測試；優化 ONNX/Sentis 量化",
      "在 UBFC 數據集上驗證 rPPG（心率 MAE 3.75 BPM，呼吸率 MAE 2.45 BPM）",
    ],
  },
  {
    id: "shyu-resume",
    name: "ShYu Resume",
    subtitle: "個人履歷 · 開源項目",
    subtitleIcon: Icons.Github,
    link: "https://github.com/shyu216/shyu-resume",
    dateRange: "2024年8月 - 進行中",
    techStack: "Next.js, Tailwind",
    bullets: [
      "開發基於 Next.js 的 i18n 履歷生成器，支援中/英/港三語切換及 A4 PDF 導出（含超連結）",
      "部署於 GitHub Pages，提供一鍵保存/列印入口",
    ],
  },
  {
    id: "carbon-2-garden",
    name: "Carbon 2 Garden",
    subtitle: "傳感器互動應用",  //   · COMP90018
    subtitleIcon: Icons.LayoutTemplate,
    link: "https://github.com/CRUVOD/CarbonTracker",
    dateRange: "2024年9月 - 2024年11月",
    techStack: "React Native, Google Maps API",
    bullets: [
      "開發 React Native 環保習慣 App，包含任務、排行榜和活動提醒",
      "集成陀螺儀和 Google Maps API，交付'久坐提醒 + 公園推薦'互動挑戰原型",
      "負責路由設計和專案骨架；完成 APK 打包發布",
    ],
  },
  // {
  //   id: "poetry-card",
  //   name: "詩詞小卡片",
  //   subtitle: "本地數據庫 · 開源項目",
  //   subtitleIcon: Icons.PackageOpen,
  //   link: "https://github.com/shyu216/ccpoems",
  //   dateRange: "2023年12月 - 2024年2月",
  //   techStack: "React Native, SQLite",
  //   bullets: [
  //     "使用 React Native + SQLite 開發古詩詞 App，實現本地 CRUD、隨機抽取、歷史記錄",
  //     "完成 Android APK 打包發布，為後續 React Native 專案累積工程經驗",
  //   ],
  // },
  {
    id: "3d-object-detection",
    name: "三維目標檢測",
    subtitle: "點雲 · 本科畢業項目",
    subtitleIcon: Icons.GraduationCap,
    link: "https://github.com/shyu216/DPC",
    dateRange: "2022年9月 - 2023年5月",
    techStack: "Python, PyTorch, Open3D",
    bullets: [
      "基於 OpenPCDet 複現 3D 目標檢測，在 KITTI 數據集生成車輛/行人/自行車檢測框",
      "使用 SLURM 集群訓練模型，透過 Open3D 完成點雲視覺化與實驗結果分析",
      "獨立完成本科畢業論文，系統整理檢測方法與實驗數據",
    ],
  },
  {
    id: "distributed-raft",
    name: "Raft 共識算法 Go 實現",
    subtitle: "分布式系統",  //  · CSCI4160
    subtitleIcon: Icons.Code,
    link: "https://github.com/shyu216/go-raft",
    dateRange: "2022年1月 - 2022年5月",
    techStack: "Go, Raft",
    bullets: [
      "研讀 Raft 論文核心原理，按論文要點實現 Raft 共識，通過 Leader 選舉與日誌複製核心測試",
      "實現支援線性一致性的分布式 KV 儲存，修復鎖競爭與日誌提交推進等並發問題，穩定通過全部測試用例",
    ],
  },
  // {
  //   id: "easy-draw-guess",
  //   name: "你畫我猜",
  //   subtitle: "即時多人遊戲 · CSCI3100",
  //   subtitleIcon: Icons.BookOpen,
  //   link: "https://github.com/easyDG",
  //   dateRange: "2022年1月 - 2022年5月",
  //   techStack: "NodeJS, Socket.IO",
  //   bullets: [
  //     "基於 MySQL 實現遊戲帳號管理，利用 Socket.IO 實現跨設備游標追蹤與即時聊天",
  //     "部署於 AWS EC2，支援多設備流暢演示",
  //   ],
  // },
  {
    id: "course-algorithm-practice",
    name: "數據與算法落地",
    subtitle: "課程項目集合",
    subtitleIcon: Icons.Code,
    link: "https://shyu216.github.io/knownoevil/study/",
    dateRange: "2021年9月 - 2024年5月",
    techStack: "SQL, Hadoop, Python",
    bullets: [
      "設計 Hadoop/MapReduce 管道用於並行 Dijkstra、PageRank、K-Means；優化大數據處理流程",
      "設計 5 表 PK/FK 模式和 8 個複雜 SQL 查詢，用於聯賽/球隊/贊助商分析",
      "構建 PostGIS 空間 SQL 用於距離、路徑規劃、單點高程和區域坡度統計",
      "使用 MDP 和獎勵函數建模 Splendor 規劃智能體；以 27/40 勝率擊敗 TA 基準",
      "使用 Doc2Vec/BiLSTM 訓練事實核查系統；處理 120 萬+ 證據句子，分類準確率 64.9%",
    ],
  },
];
