import { Icons } from "@/components/ui/icons";
import { type Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "breath-tracking",
    name: "Breath Tracking",
    subtitle: "實時呼吸監測研究",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/p7o28IXwsrs",
    dateRange: "2025年2月 - 2025年11月",
    techStack: "Python, Flask, YOLO, OpenCV",
    jobTypes: ["ML_RESEARCHER", "SOFTWARE"],
    bullets: [
      "與4DMedical持份者定期雙周會議協作，為XV Scanner工作流自動化交付實時呼吸追蹤系統",
      "訓練**YOLOv11n**進行深度圖人體檢測，優化呼吸模式信號質量（相關性↑0.5，MSE↓59.1%）",
      "將MATLAB EVM算法重構為Python實現（**OpenCV/NumPy**），放大細微呼吸運動",
      "構建實時呼吸追蹤流水線；優化**Flask**演示性能（渲染時間從1000ms降至150ms）",
    ],
  },
  {
    id: "biovis",
    name: "BioVis",
    subtitle: "MR生理信號監測研究",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/zOPQXXpSRbg",
    dateRange: "2025年5月 - 2025年11月",
    techStack: "Unity, Meta Quest 3, C#",
    jobTypes: ["ML_RESEARCHER", "SOFTWARE"],
    bullets: [
      "合著（第二作者）**SIGGRAPH Asia XR**論文投稿；負責代碼實現並參與論文撰寫",
      "主導MR生物傳感原型從導師概念到功能演示的端到端交付；獨立構建**Unity**項目（6個場景，40+腳本），完成3D與UI集成",
      "透過**ComputeShader**複現EVM算法；部署至Meta Quest 3",
      "在Quest 3上基準測試**YOLOv11n**；優化**ONNX/Sentis**量化",
      "在UBFC-rPPG數據集上驗證**rPPG**（心率MAE 3.75 BPM，呼吸率MAE 2.45 BPM）",
    ],
  },
  {
    id: "shyu-resume",
    name: "ShYu Resume",
    subtitle: "開源項目",
    subtitleIcon: Icons.Github,
    link: "https://github.com/shyu216/shyu-resume",
    dateRange: "2024年8月 - 進行中",
    techStack: "Next.js, Tailwind",
    jobTypes: ["FULLSTACK", "SOFTWARE", "DEVOPS"],
    bullets: [
      "構建基於**Next.js**的i18n履歷生成器，支援中/英/港三語切換及**A4 PDF導出**（含超連結）",
      "部署至**GitHub Pages**，提供一鍵保存/列印功能；撰寫完整README文檔便於開發者上手",
    ],
  },
  {
    id: "carbon-2-garden",
    name: "Carbon 2 Garden",
    subtitle: "傳感器交互應用",
    subtitleIcon: Icons.LayoutTemplate,
    link: "https://github.com/CRUVOD/CarbonTracker",
    dateRange: "2024年9月 - 2024年11月",
    techStack: "React Native, Google Maps API",
    jobTypes: ["FULLSTACK", "SOFTWARE"],
    bullets: [
      "構建**React Native**環保習慣應用程式，包含任務系統、排行榜和活動提醒功能",
      "實現傳感器融合，集成陀螺儀和GPS數據與**Google Maps API**，交付「久坐提醒+公園推薦」挑戰原型",
      "負責路由設計和專案骨架搭建；完成APK打包發布",
    ],
  },
  // {
  //   id: "poetry-card",
  //   name: "詩詞小卡片",
  //   subtitle: "開源項目",
  //   subtitleIcon: Icons.PackageOpen,
  //   link: "https://github.com/shyu216/ccpoems",
  //   dateRange: "2023年12月 - 2024年2月",
  //   techStack: "React Native, SQLite",
  //   bullets: [
  //     "使用React Native + SQLite開發古詩詞App，實現本地CRUD、隨機抽取、歷史記錄",
  //     "完成Android APK打包發布，為後續React Native專案累積工程經驗",
  //   ],
  // },
  {
    id: "3d-object-detection",
    name: "3D物體檢測",
    subtitle: "點雲研究",
    subtitleIcon: Icons.GraduationCap,
    link: "https://github.com/shyu216/DPC",
    dateRange: "2022年9月 - 2023年5月",
    techStack: "PyTorch, Open3D, OpenPCDet, SLURM",
    jobTypes: ["ML_RESEARCHER", "SOFTWARE"],
    bullets: [
      "基於**OpenPCDet**複現3D物體檢測，在**KITTI**數據集上生成車輛/行人/自行車檢測框；行人AP提升13.4%，車輛AP提升5.7%（超越基線）",
      "開展全面的文獻綜述和對比分析，研究最先進方法",
      "在**SLURM**集群上訓練模型；使用**Open3D**進行點雲可視化和實驗分析",
      "獨立完成本科畢業論文，系統整合研究方法和實驗結果",
    ],
  },
  {
    id: "distributed-raft",
    name: "Raft共識算法Go實現",
    subtitle: "分布式系統",
    subtitleIcon: Icons.Code,
    link: "https://github.com/shyu216/go-raft",
    dateRange: "2022年1月 - 2022年5月",
    techStack: "Go, Raft",
    jobTypes: ["SOFTWARE", "DEVOPS"],
    bullets: [
      "研讀並實現**Raft**共識算法原始論文；用**Go**編寫領導者選舉和日誌複製邏輯",
      "交付穩定的分布式KV存儲，支持自動領導者選舉和數據一致性保證；通過所有測試用例",
    ],
  },
  // {
  //   id: "easy-draw-guess",
  //   name: "你畫我猜",
  //   subtitle: "即時多人遊戲 · CSCI3100",
  //   subtitleIcon: Icons.BookOpen,
  //   link: "https://github.com/easyDG",
  //   dateRange: "2022年1月 - 2022年5月",
  //   techStack: "NodeJS, Socket.IO",
  //   bullets: [
  //     "基於MySQL實現遊戲帳號管理，利用Socket.IO實現跨設備游標追蹤與即時聊天",
  //     "部署於AWS EC2，支援多設備流暢演示",
  //   ],
  // },
  {
    id: "course-algorithm-practice",
    name: "數據與算法實踐",
    subtitle: "課程項目集合",
    subtitleIcon: Icons.Code,
    link: "https://shyu216.github.io/knownoevil/study/",
    dateRange: "2021年9月 - 2024年5月",
    techStack: "SQL, Hadoop, Python",
    jobTypes: ["SOFTWARE", "DEVOPS", "ML_RESEARCHER"],
    bullets: [
      "設計**Hadoop/MapReduce**流水線並行實現**Dijkstra**、**PageRank**、**K-Means**；優化大數據處理流程",
      "設計5表主鍵/外鍵架構和8個複雜**SQL**查詢，用於聯賽/球隊/贊助商分析",
      "構建**PostGIS**空間SQL實現距離計算、路徑規劃、單點高程和區域坡度統計",
      "構建Splendor規劃智能體，使用**MDP**和獎勵函數建模；以27/40勝率擊敗TA基準（班級排名第4）",
      "訓練事實核查系統，採用**Doc2Vec/BiLSTM**；處理120萬+證據句子，分類準確率達64.9%",
    ],
  },
];
