import { Icons } from "@/components/ui/icons";
import { type Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "biovis",
    name: "BioVis",
    subtitle: "碩士畢業設計（部分）",
  subtitleIcon: Icons.GraduationCap,
    link: "https://github.com/shyu216/Unity-Quest3-EVM",
  dateRange: "2025年5月 - 2025年8月",
  techStack: "Unity, Meta Quest 3, C#",
    bullets: [
      "基於Unity開發Meta Quest 3 MR健康監測應用，探索並實現多種無接觸生理信號檢測方案（如歐拉視訊放大、rPPG），實現對頭顯視野內他人心率與呼吸頻率的檢測。",
      "利用ComputeShader並行加速圖像處理，複現EVM算法，提升信號檢測效率。",
      "獨立開發包含6個場景、10餘種材質、40餘個腳本，整合3D模型、音效資源及豐富UI的Unity項目。",
    ],
    rank: 1,
  },
  {
    id: "shyu-resume",
    name: "個人簡歷",
    subtitle: "開源項目",
  subtitleIcon: Icons.Github,
    link: "https://github.com/shyu216/shyu-resume",
  dateRange: "2024年8月 - 進行中",
  techStack: "Next.js, Tailwind",
    bullets: [
      "基於Next.js SSR特性開發，支援中、英、港三語切換，兼容主流靜態託管平台。",
      "開發基於 Next.js 的 i18n 履歷生成器，支援 A4 PDF 導出與三語。",
      "已部署於GitHub Pages（https://shyu216.github.io/shyu-resume），右上角按鈕可直達或保存PDF。",
    ],
    rank: 1,
  },
  {
    id: "carbon-2-garden",
    name: "Carbon 2 Garden",
    subtitle: "COMP90018大作業",
  subtitleIcon: Icons.LayoutTemplate,
    link: "https://github.com/CRUVOD/CarbonTracker",
  dateRange: "2024年9月 - 2024年11月",
  techStack: "React Native, Firebase",
    bullets: [
      "利用React Native協作開發綠色生活習慣App，開發健康生活任務系統與排行榜，涵蓋交通工具推薦、運動提醒等功能。",
      "負責路由設計及多種感應器原始數據採集，實現基於感應器的互動挑戰與Google Maps定位任務，並發布開源安裝包。",
    ],
  rank: 1,
  },
  {
    id: "poetry-card",
    name: "詩詞小卡片",
    subtitle: "開源項目",
  subtitleIcon: Icons.PackageOpen,
    link: "https://github.com/shyu216/ccpoems",
  dateRange: "2023年12月 - 進行中",
  techStack: "React Native, SQLite",
    bullets: [
      "使用React Native與SQLite開發古詩詞App，實現古詩詞本地數據庫存儲，支持增刪改查等操作。",
      "實現簡潔UI與滑動切換、隨機抽取、歷史記錄等功能，已在GitHub開源並發布Android安裝包。",
    ],
    rank: 2,
  },
  {
    id: "3d-object-detection",
    name: "DPC：密集化點雲的三維目標檢測",
    subtitle: "本科畢業設計",
  subtitleIcon: Icons.GraduationCap,
    link: "https://github.com/shyu216/DPC",
  dateRange: "2022年9月 - 2023年5月",
  techStack: "Python, PyTorch, Open3D",
    bullets: [
      "深入探索OpenPCDet代碼庫和KITTI數據集，複現相關三維目標檢測與深度補全方法，推理生成行人、自行車、車輛的三維檢測框。",
      "利用SLURM GPU集群進行訓練與測試，結合Open3D進行點雲可視化與處理，系統整理實驗結果並完成畢業答辯。",
    ],
  rank: 1,
  },
  {
    id: "easy-draw-guess",
    name: "你畫我猜小遊戲",
    subtitle: "CSCI3100大作業",
  subtitleIcon: Icons.BookOpen,
    link: "https://github.com/easyDG",
  dateRange: "2022年1月 - 2022年5月",
  techStack: "MySQL, ExpressJS, NodeJS, Socket.IO",
    bullets: [
      "基於MySQL實現遊戲帳號增刪改查，利用Socket.IO實現跨設備光標追蹤、遊戲房間與即時聊天。",
      "部署於AWS EC2雲端，支持多設備流暢演示。",
    ],
    rank: 3,
  },
];
