import {
  PackageOpen,
  BookOpen,
  Sun,
  MoonStar,
  Zap,
  Github,
  Youtube,
  Mail,
  Linkedin,
  Briefcase,
  ExternalLink,
  PhoneCall,
  Layers,
  FileBadge,
  Star,
  Users,
  Link,
  Bot,
  GraduationCap,
  Code,
  School,
  Building2,
  LayoutTemplate,
  Smartphone,
  MessagesSquare
} from "lucide-react";

import type { LucideIcon } from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  PackageOpen: PackageOpen,
  BookOpen: BookOpen,
  Sun: Sun,
  Moon: MoonStar,
  Lightning: Zap,
  Github: Github,
  Youtube: Youtube,
  Mail: Mail,
  Linkedin: Linkedin,
  Briefcase: Briefcase,
  School: School,
  OpenLink: ExternalLink,
  PhoneCall: PhoneCall,
  Stack: Layers,
  FileBadge: FileBadge,
  Star: Star,
  Users: Users,
  Link: Link,
  Bot: Bot,
  GraduationCap: GraduationCap,
  Code: Code,
  Building: Building2,
  LayoutTemplate: LayoutTemplate,
  SmartPhone: Smartphone,
  Wechat: MessagesSquare,
} as const;
