import { Icons } from "@/components/ui/icons";
import { type Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "biovis",
    name: "BioVis",
    subtitle: "MR Physiological Signal Monitoring · Research Project",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/zOPQXXpSRbg",
    dateRange: "May 2025 – Nov 2025",
    techStack: "Unity, Meta Quest 3, C#",
    bullets: [
      "Developed a Meta Quest 3 MR health app in Unity, implementing Eulerian Video Magnification and rPPG for contactless heart and respiratory rate measurement.",
      "Used ComputeShader for parallel image processing and reproduced the EVM algorithm.",
      "Independently developed a Unity project with 6 scenes, over 10 materials, and over 40 scripts, integrating 3D models, audio assets, and a rich UI.",
    ],
    rank: 1,
  },
  {
    id: "shyu-resume",
    name: "ShYu Resume",
    subtitle: "Personal Resume · Open Source Project",
    subtitleIcon: Icons.Github,
    link: "https://github.com/shyu216/shyu-resume",
    dateRange: "Aug 2024 – Present",
    techStack: "Next.js, Tailwind",
    bullets: [
      "Developed an i18n resume web app in Next.js, compatible with most static hosts.",
      "Built i18n resume generator with Next.js, supporting A4 PDF export and 3 languages.",
      "Hosted on GitHub Pages (https://shyu216.github.io/shyu-resume) with a top-right button for direct PDF view or download.",
    ],
    rank: 1,
  },
  {
    id: "carbon-2-garden",
    name: "Carbon 2 Garden",
    subtitle: "Sensor Interactive App · COMP90018",
    subtitleIcon: Icons.LayoutTemplate,
    link: "https://github.com/CRUVOD/CarbonTracker",
    dateRange: "Aug 2024 – Nov 2024",
    techStack: "React Native, Firebase",
    bullets: [
      "Built an eco-habit app with React Native, including task system, leaderboard, and activity reminders.",
      "Designed router, acquired sensor data, implemented sensor-based challenges and Google Maps tasks, released APK.",
    ],
    rank: 1,
  },
  {
    id: "poetry-card",
    name: "Poetry Card",
    subtitle: "Local Database · Open Source Project",
    subtitleIcon: Icons.PackageOpen,
    link: "https://github.com/shyu216/ccpoems",
    dateRange: "Dec 2023 – Feb 2024",
    techStack: "React Native, SQLite",
    bullets: [
      "Developed a Chinese poetry app with React Native and SQLite, supporting local database CRUD.",
      "Added swipe navigation, random selection, history; open-sourced on GitHub and released Android APK.",
    ],
    rank: 2,
  },
  {
    id: "3d-object-detection",
    name: "3D Object Detection",
    subtitle: "Point Cloud · Bachelor Thesis",
    subtitleIcon: Icons.GraduationCap,
    link: "https://github.com/shyu216/DPC",
    dateRange: "Aug 2022 – Jul 2023",
    techStack: "Python, PyTorch, Open3D",
    bullets: [
      "Reproduced 3D object detection and depth completion with OpenPCDet on KITTI, generated 3D bounding boxes for pedestrians, cyclists, and vehicles.",
      "Trained and tested models on SLURM GPU clusters, used Open3D for point cloud visualization, documented results for thesis defense.",
    ],
    rank: 1,
  },
  {
    id: "distributed-raft",
    name: "Raft Consensus Algorithm (Go Implementation)",
    subtitle: "Distributed Systems · CSCI4160",
    subtitleIcon: Icons.Code,
    link: "https://github.com/shyu216/go-raft",
    dateRange: "Jan 2022 – May 2022",
    techStack: "Go, Raft",
    bullets: [
      "Implemented the Raft consensus algorithm based on the MIT 6.824 framework, passing core tests for leader election and log replication.",
      "Built a linearizable key-value store, fixing classic distributed concurrency bugs such as lock contention and commit advancement.",
    ],
    rank: 1,
  },
  {
    id: "easy-draw-guess",
    name: "Easy Draw & Guess",
    subtitle: "CSCI3100 Major Assignment",
    subtitleIcon: Icons.BookOpen,
    link: "https://github.com/easyDG",
    dateRange: "Jan 2022 – May 2022",
    techStack: "MySQL, ExpressJS, NodeJS, Socket.IO",
    bullets: [
      "Implemented user account CRUD with MySQL; used Socket.IO for cursor tracking, game rooms, and real-time chat.",
      "Deployed on AWS EC2 for multi-device demo.",
    ],
    rank: 3,
  },
];
