import { Icons } from "@/components/ui/icons";
import { type Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "biovis",
    name: "BioVis",
    subtitle: "Mixed Reality Biosensing · Research Project",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/zOPQXXpSRbg",
    dateRange: "May 2025 – Nov 2025",
    techStack: "Unity, Meta Quest 3, C#",
    bullets: [
      "Second author on a Siggraph Asia XR submission; built the MR physiological-signal prototype.",
      "Solo-built a 6-scene Unity project with 40+ scripts, integrating 3D assets and rich UI.",
      "Used ComputeShader for parallel image processing, reproducing EVM for real-time MR on Quest 3.",
      "Reproduced rPPG and reached 17.7 FPS real-time inference on a 2080 Ti (host side).",
      "Evaluated ONNX, Sentis, and CPU inference, selecting the ComputeShader path given Quest 3 constraints.",
      "Experimented with YOLO v11 nano INT8 quantization; deferred deployment due to accuracy limits, leaving room for tuning.",
    ],
    rank: 1,
  },
  {
    id: "shyu-resume",
    name: "ShYu Resume",
    subtitle: "Personal Resume · Open Source Project",
    subtitleIcon: Icons.Github,
    link: "https://github.com/shyu216/shyu-resume",
    dateRange: "Aug 2024 – Present",
    techStack: "Next.js, Tailwind",
    bullets: [
      "Built a Next.js i18n resume generator with zh/en/zh-hk switching and A4 PDF export with links.",
      "Deployed to GitHub Pages with a one-click save/print entry.",
    ],
    rank: 1,
  },
  {
    id: "carbon-2-garden",
    name: "Carbon 2 Garden",
    subtitle: "Sensor Interactive App · COMP90018",
    subtitleIcon: Icons.LayoutTemplate,
    link: "https://github.com/CRUVOD/CarbonTracker",
    dateRange: "Aug 2024 – Nov 2024",
    techStack: "React Native, Firebase",
    bullets: [
      "Built a React Native eco-habit app with tasks, leaderboard, and activity reminders.",
      "Integrated gyroscope data and Google Maps API to ship a \"sit-less + park recommendation\" interactive challenge prototype.",
      "Designed routing and project scaffolding, delivering the APK release.",
    ],
    rank: 1,
  },
  {
    id: "poetry-card",
    name: "Poetry Card",
    subtitle: "Local Database · Open Source Project",
    subtitleIcon: Icons.PackageOpen,
    link: "https://github.com/shyu216/ccpoems",
    dateRange: "Dec 2023 – Feb 2024",
    techStack: "React Native, SQLite",
    bullets: [
      "Built a Chinese poetry app with React Native + SQLite, enabling local CRUD, random picks, and history.",
      "Shipped the Android APK and captured engineering learnings for later React Native work.",
    ],
    rank: 2,
  },
  {
    id: "3d-object-detection",
    name: "3D Object Detection",
    subtitle: "Point Cloud · Bachelor Thesis",
    subtitleIcon: Icons.GraduationCap,
    link: "https://github.com/shyu216/DPC",
    dateRange: "Aug 2022 – Jul 2023",
    techStack: "Python, PyTorch, Open3D",
    bullets: [
      "Reproduced 3D object detection with OpenPCDet on KITTI, generating boxes for cars, pedestrians, and cyclists.",
      "Trained on SLURM clusters and used Open3D for point-cloud visualization and result analysis.",
      "Completed the bachelor thesis independently, organizing methods and experimental data.",
    ],
    rank: 1,
  },
  {
    id: "distributed-raft",
    name: "Raft Consensus Implementation in Go",
    subtitle: "Distributed Systems · CSCI4160",
    subtitleIcon: Icons.Code,
    link: "https://github.com/shyu216/go-raft",
    dateRange: "Jan 2022 – May 2022",
    techStack: "Go, Raft",
    bullets: [
      "Implemented the Raft consensus algorithm based on the MIT 6.824 framework, passing core tests for leader election and log replication.",
      "Built a linearizable key-value store, fixing classic distributed concurrency bugs such as lock contention and commit advancement.",
    ],
    rank: 1,
  },
  {
    id: "easy-draw-guess",
    name: "Easy Draw & Guess",
    subtitle: "CSCI3100 Major Assignment",
    subtitleIcon: Icons.BookOpen,
    link: "https://github.com/easyDG",
    dateRange: "Jan 2022 – May 2022",
    techStack: "MySQL, ExpressJS, NodeJS, Socket.IO",
    bullets: [
      "Implemented user account CRUD with MySQL; used Socket.IO for cursor tracking, game rooms, and real-time chat.",
      "Deployed on AWS EC2 for multi-device demo.",
    ],
    rank: 3,
  },
];
