import { Icons } from "@/components/ui/icons";
import { type Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "biovis",
    name: "BioVis",
    subtitle: "Mixed Reality Biosensing · Research Project",
    subtitleIcon: Icons.GraduationCap,
    link: "https://youtu.be/zOPQXXpSRbg",
    dateRange: "May 2025 – Nov 2025",
    techStack: "Unity, Meta Quest 3, C#",
    bullets: [
      "Co-authored (2nd) a Siggraph Asia XR submission; built the MR biosensing prototype.",
      "Solo-built a Unity project with 6 scenes and 40+ scripts, integrating 3D assets and UI.",
      "Used ComputeShader for parallel image processing; reproduced EVM; deployed a Quest 3 real-time MR prototype.",
      "Evaluated ONNX and Sentis quantization/inference; benchmarked YOLO v11 nano in real time on Quest 3.",
      "Reproduced multiple rPPG algorithms and validated across datasets, delivering academic-to-edge real-time deployment.",
    ],
    rank: 1,
  },
  {
    id: "shyu-resume",
    name: "ShYu Resume",
    subtitle: "Personal Resume · Open Source Project",
    subtitleIcon: Icons.Github,
    link: "https://github.com/shyu216/shyu-resume",
    dateRange: "Aug 2024 – Present",
    techStack: "Next.js, Tailwind",
    bullets: [
      "Built a Next.js i18n resume generator with tri-language (ZH/EN/HK) switching and A4 PDF export (hyperlinks included).",
      "Deployed to GitHub Pages with one-click save/print.",
    ],
    rank: 1,
  },
  {
    id: "carbon-2-garden",
    name: "Carbon 2 Garden",
    subtitle: "Sensor Interactive App · COMP90018",
    subtitleIcon: Icons.LayoutTemplate,
    link: "https://github.com/CRUVOD/CarbonTracker",
    dateRange: "Sep 2024 – Nov 2024",
    techStack: "React Native, Firebase",
    bullets: [
      "Built a React Native eco-habit app with tasks, leaderboards, and activity reminders.",
      "Integrated gyroscope and Google Maps API to ship a \"sedentary alert + park recommendation\" challenge prototype.",
      "Owned routing and project skeleton; shipped the APK.",
    ],
    rank: 1,
  },
  {
    id: "poetry-card",
    name: "Poetry Card",
    subtitle: "Local Database · Open Source Project",
    subtitleIcon: Icons.PackageOpen,
    link: "https://github.com/shyu216/ccpoems",
    dateRange: "Dec 2023 – Feb 2024",
    techStack: "React Native, SQLite",
    bullets: [
      "Built a Chinese poetry app with React Native + SQLite, enabling local CRUD, random draws, and history.",
      "Shipped the Android APK, accruing React Native delivery experience for later projects.",
    ],
    rank: 2,
  },
  {
    id: "3d-object-detection",
    name: "3D Object Detection",
    subtitle: "Point Cloud · Bachelor Thesis",
    subtitleIcon: Icons.GraduationCap,
    link: "https://github.com/shyu216/DPC",
    dateRange: "Sep 2022 – May 2023",
    techStack: "Python, PyTorch, Open3D",
    bullets: [
      "Reproduced 3D object detection on OpenPCDet, generating vehicle/pedestrian/cyclist boxes on KITTI.",
      "Trained on a SLURM cluster; used Open3D for point-cloud visualization and experiment analysis.",
      "Completed the bachelor thesis independently, consolidating methods and results.",
    ],
    rank: 1,
  },
  {
    id: "distributed-raft",
    name: "Raft Consensus Implementation in Go",
    subtitle: "Distributed Systems · CSCI4160",
    subtitleIcon: Icons.Code,
    link: "https://github.com/shyu216/go-raft",
    dateRange: "Jan 2022 – May 2022",
    techStack: "Go, Raft",
    bullets: [
      "Implemented Raft per the paper; passed leader election and log replication tests.",
      "Delivered a linearizable distributed KV store; fixed lock contention and log commit issues; passed all tests.",
    ],
    rank: 1,
  },
  {
    id: "easy-draw-guess",
    name: "Easy Draw & Guess",
    subtitle: "Real-time Multiplayer Game · CSCI3100",
    subtitleIcon: Icons.BookOpen,
    link: "https://github.com/easyDG",
    dateRange: "Jan 2022 – May 2022",
    techStack: "NodeJS, Socket.IO",
    bullets: [
    "Built MySQL account management and Socket.IO cross-device cursor tracking plus real-time chat.",
    "Deployed on AWS EC2 for smooth multi-device demos.",
    ],
    rank: 3,
  },
  {
    id: "course-algorithm-practice",
    name: "Data & Algorithm Delivery",
    subtitle: "Course Project Collection",
    subtitleIcon: Icons.Code,
    link: "https://shyu216.github.io/knownoevil/study/",
    dateRange: "Sep 2021 – May 2024",
    techStack: "SQL, Hadoop, Python",
    bullets: [
      "Designed Hadoop/MapReduce pipelines for parallel Dijkstra, PageRank, K-Means; optimized big-data processing flow.",
      "Designed a 5-table PK/FK schema and 8 complex SQL queries (multi-join/subquery/custom formulas) for league/team/sponsor analytics.",
      "Built PostGIS spatial SQL for distance, routing, single-point elevation, and area slope statistics.",
      "Splendor planning agents modeled with MDP and reward functions; tuned to beat the TA baseline (27–13).",
    ],
    rank: 1,
  },
];
