import { type Summary } from "@/types/summary";

export const summary: Summary = {
  fullstack: "Full Stack Developer with 10 months of startup production experience, delivering end-to-end cloud-native solutions in Agile processes. Led a 3-person cross-functional team to deliver 80+ features on a Next.js/AWS platform, automating deployments via CI/CD pipelines to reduce deployment effort by 90%. Proficient in TypeScript, React, Node.js and REST API development, spanning React Native mobile apps to AWS cloud infrastructure, and able to communicate technical solutions clearly to non-technical stakeholders.",

  software: "Software Engineer with production experience designing and delivering scalable systems — from event-driven payment architectures to real-time data processing pipelines. Architected AWS event-driven backends (EventBridge, Lambda, DynamoDB) supporting payment workflows and automated notifications; built real-time biosensing data pipelines achieving 24.7 FPS / 40ms low-latency processing. Led cross-functional teams in Agile environments to deliver 80+ production features. Skilled in system design, API development, concurrency, and microservices, using TypeScript, Python and Node.js.",

  ml: "AI/ML Engineer with experience in computer vision (CV) and mixed reality (MR) systems. During my MSc I focused on building clinical-grade CV/MR systems, using PyTorch, YOLO object detection and OpenCV to develop real-time data pipelines for 4DMedical's XV Scanner, achieving 24.7 FPS / 40ms latency. During undergraduate studies I contributed to a 9-month 3D object recognition CV research project. Proficient in Python, machine learning frameworks, and productionizing CV algorithms.",

  devops: "Cloud/DevOps Engineer focused on Infrastructure as Code (IaC) and observability for cloud-native platforms. At a startup I used AWS CDK, Terraform and GitHub Actions to automate CI/CD pipelines, reducing deployment effort by 90%; implemented IaC practices including automated rollbacks and environment management. Built event-driven systems based on AWS EventBridge/SES and established end-to-end monitoring with cloud-native observability tools. Skilled in cross-team technical communication.",

  default: "Versatile technical professional with an MSc in Computer Science and nearly 3 years of practical experience from CV/ML research to full-stack development. During undergraduate studies I participated in a 9-month 3D object recognition computer vision research project; I then worked 10 months as a full-stack developer at a startup, leading a cross-functional team to deliver 80+ cloud-native features on Next.js/AWS and reducing deployment effort by 90% through CI/CD automation; during my MSc I focused on CV/MR system development, using PyTorch, YOLO and OpenCV to build clinical-grade real-time data pipelines achieving 24.7 FPS / 40ms latency. Proficient in TypeScript, Python, React, Node.js and AWS cloud infrastructure, with the ability to bridge technical and non-technical stakeholders."
};